---
abstract: 'Perl extension for DVB terrestrial recording, epg, and scanning '
author:
  - 'Steve Price <cpan@sdprice.plus.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Linux-DVB-DVBT
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: 0
  Data::Dumper: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 0
  POSIX: 0
  Pod::Coverage: 0.18
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
version: 2.18
